version: 2.1

orbs:
  python: cjw296/python-ci@2

jobs:
  check-package:
    parameters:
      image:
        type: string
      python:
        type: string
        default: "python"
    docker:
      - image: << parameters.image >>
    steps:
      - python/check-package:
          package: "mock"
          test:
          - run:
              name: "Import package"
              command: << parameters.python >> -c "import mock"


common: &common
  jobs:

    - python/pip-run-tests:
        matrix:
          parameters:
            image:
              - circleci/python:3.6
              - circleci/python:3.7
              - circleci/python:3.8
              - circleci/python:3.9
              - pypy:3.6

    - python/coverage:
        name: coverage
        requires:
          - python/pip-run-tests

    - python/pip-docs:
        name: docs
        requires:
          - coverage

    - python/pip-setuptools-build-package:
        name: package
        requires:
          - docs
        filters:
          branches:
            only: master

    - check-package:
        matrix:
          parameters:
            image:
              - circleci/python:3.6
              - circleci/python:3.7
              - circleci/python:3.8
              - circleci/python:3.9
              - pypy:3.6
        requires:
          - package

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - check-package

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: master
